import type { Video } from "../types/video";

export const mockVideos: Video[] = [
  {
    id: "mock-001",
    url: "https://www.bilibili.com/video/BV1234567890",
    platform: "B站",
    author: "周六野Zoey",
    title: "15分钟居家全身燃脂",
    bodyPart: "全身",
    duration: "15min",
    intensity: "中强度",
    equipment: "瑜伽垫",
    trainingType: "有氧",
    specialTags: ["无跳跃", "低能量可练"],
    note: "适合没有太多时间时快速启动。",
    createdAt: "2026-06-01T08:00:00.000Z",
    lastPracticedAt: null,
    completedCount: 0,
    userPreference: "常练",
  },
  {
    id: "mock-002",
    url: "https://www.xiaohongshu.com/explore/mock",
    platform: "小红书",
    author: "梨子肩颈舒缓",
    title: "久坐肩颈放松跟练",
    bodyPart: "肩背",
    duration: "10min",
    intensity: "低强度",
    equipment: "无器械",
    trainingType: "拉伸",
    specialTags: ["久坐急救", "温柔拉伸"],
    note: "适合工作间隙舒缓肩颈。",
    createdAt: "2026-06-02T08:00:00.000Z",
    lastPracticedAt: null,
    completedCount: 0,
    userPreference: "收藏",
  },
  {
    id: "mock-003",
    url: "https://www.keep.com/training/mock",
    platform: "Keep",
    author: "Keep官方",
    title: "臀腿塑形基础训练",
    bodyPart: "臀腿",
    duration: "20min",
    intensity: "中高强度",
    equipment: "弹力带",
    trainingType: "力量",
    specialTags: ["蜜桃臀启动", "线条训练"],
    note: "下肢塑形日使用。",
    createdAt: "2026-06-03T08:00:00.000Z",
    lastPracticedAt: null,
    completedCount: 0,
    userPreference: "挑战",
  },
];
